from helpers.git_helper import commit_and_push_changes, create_pull_request

def create_pull_request_tool(workspace_path: str, pr_title: str = None, pr_body: str = None):
    """
    Commits, pushes changes, and creates a GitHub PR.
    Returns PR URL.
    """
    branch_name = commit_and_push_changes(workspace_path)
    pr_title = pr_title or f"Automated PR for {branch_name}"
    pr_body = pr_body or "Generated by AI onboarding tool."
    pr_url = create_pull_request(branch_name, pr_title, pr_body)
    return f"✅ PR created successfully: {pr_url}"
